set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set -g mouse on
set -g history-limit 100000
set -g set-clipboard on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g status-keys vi
setw -g mode-keys vi
set -sg escape-time 10
set -g allow-rename off

bind -T copy-mode-vi WheelUpPane send-keys -X -N 3 scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X -N 3 scroll-down

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# Source machine-local overrides
source-file -q ~/.tmux.conf.local
